version: "3.3"

services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 23000:1433
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: "HelloW0rld"
     
  
  application:
    image: lechampdk/todoimage
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: 
      - mssql-db
    ports: 
      - 23001:80
