version: "3.3"

services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 23000:1433
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: "HelloW0rld"
     
  
  application:
    image: lechampdk/todoit
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: 
      - mssql-db
      - elasticsearch
    ports: 
      - 23001:80

  webstrom:
    image: lechampdk/todoitwebstrom
    depends_on: 
      - application
    ports: 
      - 23002:80

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic
     
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elastic
